### ISSUE TITLE
Comparing with string constant does not work

### ISSUE THREAD

**Issue by githubuser0xFFFF** [DuffsDevice/tiny-utf8#24] opened 2019-05-15 08:37 UTC
Hi,

The following code:

```cpp
    utf8_string teststring = "µm";
    if (teststring == "µm")
    {
    	std::cout << "teststring == µm --> true" << std::endl;
    }

    if (teststring == utf8_string("µm"))
    {
    	std::cout << "teststring == utf8_string(\"µm\") --> true" << std::endl;
    }
```
produces the following output:

`teststring == utf8_string("µm") --> true`

So the comparison with the string constant fails.

**Comment by DuffsDevice** [comment] 2019-05-15 21:12
I'm sorry for the inconvenience, there was a quite obvious bug still left (which I somewhat overlooked).
Hope, the issue is fixed by now 😌 

Thank you,
Jakob

**Comment by DuffsDevice** [comment] 2019-05-17 14:10
Does it work for you now?

**Comment by DuffsDevice** [comment] 2019-05-22 20:46
Feel free to open the ticket again, if there should still be any issues left.

**Closed** 2019-05-22 20:46 UTC
Labels: bug
